name: Save tracked projects downloads
on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run script
        run: ./save_projects_downloads.sh