name: Force update backend data
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run script
        run: ./update_project_backend.sh  