name: Force update backend data
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Make script executable
        run: chmod +x /scripts/update_tracked_projects_backend.sh
      - name: Run script
        run: ./scripts/update_tracked_projects_backend.sh  